from agents.video_agent import VideoAgent
from models.content import Content
from models.scene import Scene


content = Content(

    topic="Nifty 50 Today",

    content_type="Shorts",

    script="",

    title="",

    description="",

    tags="",

    thumbnail_prompt="",

    status="Approved"

)

# Existing audio generated by VoiceAgent
content.audio_path = "output/audio/nifty_50_today.mp3"

scenes = [

    Scene(

        scene=1,

        sentence="आज बाजार में तेजी आई।",

        keyword="Indian Stock Market",

        search_query="Indian stock market trading screen",

        video_type="Stock Market",

        mood="Positive",

        duration=3,

        video_path="output/raw_videos/scene_1.mp4"

    ),

    Scene(

        scene=2,

        sentence="निवेशकों में खुशी है।",

        keyword="Happy Investor",

        search_query="Indian investor smiling with laptop",

        video_type="People",

        mood="Positive",

        duration=3,

        video_path="output/raw_videos/scene_2.mp4"

    )

]

print("=" * 40)
print("      Testing Video Agent")
print("=" * 40)

agent = VideoAgent()

video = agent.generate(

    content,

    scenes

)

print()

print("=" * 40)
print("      Video Created")
print("=" * 40)

print()

print(video)